server:
  port: 25505

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://harmonyosnchu.com:3306/trainer?useUnicode=true&characterEncoding=utf8
    username: trainer
    password: trainer
    hikari:
      #最小空闲连接数
      minimum-idle: 10
      #连接池最大连接数
      maximum-pool-size: 30

mybatis:
  #mybatis扫描mapper文件的位置
  mapper-locations: classpath:mapper/*Mapper.xml

  # 控制台打印sql日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
